// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const white1: string;
export const black1: string;
export const blue1: string;
export const grey1: string;
export const errorRed: string;
export const checkedGreen: string;
export const focusBlue: string;
export const navLink: string;
