// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const clickOff: string;
export const links: string;
export const menuClosed: string;
export const menuOpen: string;
